import { Inter } from "next/font/google";
import Image from "next/image";
import "./globals.css";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.variable} font-sans antialiased`}>
        <header className="border-b border-gray-200 bg-white">
          <div className="mx-auto grid max-w-[1440px] grid-cols-[240px_1fr] px-8 py-4">
            <div className="flex items-center justify-center gap-3">
              <Image
                src="/angkorlisting-logo.png"
                alt="AngkorListing Logo"
                width={40}
                height={40}
                className="object-contain"
              />
              <h1 className="text-2xl font-semibold text-gray-900">
                AngkorListing
              </h1>
            </div>
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
